name: Deploy to Streamlit Cloud with Docker

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (Docker build support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add Docker Hub credentials as GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add Docker Hub password or token as GitHub Secrets

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t evanw22/bostonhousepricing:latest .

      # Step 5: Push Docker image to Docker Hub (or another container registry)
      - name: Push Docker image
        run: |
          docker push evanw22/bostonhousepricing:latest

      # Step 6: Trigger deployment to Streamlit Cloud (optional step)
      # In Streamlit Cloud, it typically auto-deploys when you push to GitHub,
      # but if using Docker, you may need to trigger this manually or via API if desired.
      # Note: Currently, Streamlit Cloud does not directly support Docker deployment via GitHub Actions.
      # This step can be omitted if you want to rely on Streamlit's default GitHub integration.
